import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { babyName, sleepData, foodData, weightData } = req.body;

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        error: "GEMINI_API_KEY environment variable is not configured. Please add it in Vercel project settings."
      });
    }

    const { GoogleGenAI } = await import('@google/genai');

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });

    const prompt = `
Generate a warm, brief, and highly encouraging weekly progress summary for my baby, ${babyName || 'the baby'}.
The summary must analyze recent metrics, celebrate positive steps, and offer supportive parenting insight.

Current Week's Data Summary:
- SLEEP:
${JSON.stringify(sleepData, null, 2)}

- FOOD/FEEDING:
${JSON.stringify(foodData, null, 2)}

- WEIGHT PROGRESS:
${JSON.stringify(weightData, null, 2)}

Guidelines:
1. Speak in a friendly, empathetic, and professional tone.
2. Celebrate small milestones (e.g., getting enough sleep, solid weigh-ins, regular bottle feeds/solid sessions).
3. Do not give strict medical advice, but offer gentle, comforting support like a seasoned pediatric nurse or caring infant developmental specialist.
4. Keep the output neat, structured with bullet points under 2-3 concise headers, and clearly written in Markdown. Keep it brief (around 150-200 words).
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are an encouraging and loving pediatric specialist and assistant who helps parent evaluate their baby's sleep, eating, and growth routines."
      }
    });

    res.json({ text: response.text || "No response text generated by Gemini." });
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    res.status(500).json({ error: error.message || "An unexpected error occurred during analysis" });
  }
}
