import dotenv from "dotenv";
dotenv.config();

import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route for Gemini analysis
  app.post("/api/gemini/analyze", async (req, res) => {
    try {
      const { babyName, sleepData, foodData, weightData } = req.body;

      if (!process.env.GEMINI_API_KEY) {
        return res.status(500).json({
          error: "GEMINI_API_KEY environment variable is not configured. Please add it in Settings > Secrets."
        });
      }

      const ai = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      const prompt = `
Generate a warm, brief, and highly encouraging weekly progress summary for my baby, ${babyName || 'the baby'}.
The summary must analyze recent metrics, celebrate positive steps, and offer supportive parenting insight.

Current Week's Data Summary:
- SLEEP:
${JSON.stringify(sleepData, null, 2)}

- FOOD/FEEDING:
${JSON.stringify(foodData, null, 2)}

- WEIGHT PROGRESS:
${JSON.stringify(weightData, null, 2)}

Guidelines:
1. Speak in a friendly, empathetic, and professional tone.
2. Celebrate small milestones (e.g., getting enough sleep, solid weigh-ins, regular bottle feeds/solid sessions).
3. Do not give strict medical advice, but offer gentle, comforting support like a seasoned pediatric nurse or caring infant developmental specialist.
4. Keep the output neat, structured with bullet points under 2-3 concise headers, and clearly written in Markdown. Keep it brief (around 150-200 words).
`;

      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an encouraging and loving pediatric specialist and assistant who helps parent evaluate their baby's sleep, eating, and growth routines."
        }
      });

      res.json({ text: response.text || "No response text generated by Gemini." });
    } catch (error: any) {
      console.error("Gemini API Error:", error);
      res.status(500).json({ error: error.message || "An unexpected error occurred during analysis" });
    }
  });

  // API Route for Feeding Intervals & Next Feed Predictions
  app.post("/api/gemini/feeding-insight", async (req, res) => {
    try {
      const { babyName, recentFeeds } = req.body;

      if (!process.env.GEMINI_API_KEY) {
        return res.status(500).json({
          error: "GEMINI_API_KEY environment variable is not configured. Please add it in Settings > Secrets."
        });
      }

      const ai = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      const prompt = `
You are an expert pediatric nurse and infant feeding schedule specialist. Analyze the following chronology of recent feeds for ${babyName || 'the baby'} to determine:
1. The average gap/interval between consecutive feeds.
2. The recommended next feeding time based on the last recorded feed.
3. Supportive and friendly commentary, patterns found (e.g. formula vs breastfeeding differences if any), and custom guidance.

Recent chronological feed events:
${JSON.stringify(recentFeeds, null, 2)}

Instructions:
- If there are fewer than 2 feeding sessions, warn gently in raw analysisText and suggest a default next feed time 3 hours after the last session, and write some general warm tips on tracking.
- If there are multiple sessions, calculate the actual time differences in minutes and find the average.
- Suggest a specific next feeding time (e.g., "05:15 PM") that adds the average gap (or a baseline 3-hour gap if data is sparse) to the last feed.
- Provide a highly encouraging, helpful Markdown analysis (100-150 words) under \`analysisText\`. Celebrates the parent's efforts!
`;

      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a professional pediatric consultant who provides intelligence about infant feeding patterns. Always return a perfectly structured JSON object matching the requested schema.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              averageGapMinutes: { 
                type: Type.INTEGER, 
                description: "The calculated average interval in minutes between feeds. Use 180 as default or if there are insufficient sessions." 
              },
              suggestedNextTime: { 
                type: Type.STRING, 
                description: "The calculated ideal next feeding time in HH:MM AM/PM format (e.g., '05:30 PM')." 
              },
              reasoning: { 
                type: Type.STRING, 
                description: "A short sentence explaining how this timing was estimated (e.g., 'Based on a 3h 15m average gap after your last feed at 2:00 PM.')." 
              },
              analysisText: { 
                type: Type.STRING, 
                description: "Extremely warm, supportive Markdown paragraph analysing the baby's timing routines, highlighting breast/bottle consistency, and providing developmental reassurance." 
              }
            },
            required: ["averageGapMinutes", "suggestedNextTime", "reasoning", "analysisText"]
          }
        }
      });

      const resultText = response.text || "{}";
      const parsedData = JSON.parse(resultText);
      res.json(parsedData);
    } catch (error: any) {
      console.error("Gemini Feeding Insight Error:", error);
      res.status(505).json({ error: error.message || "Failed to generate feeding insights" });
    }
  });

  // Vite middleware for development or serving files for production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
